name: CI/CD for ASP.NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Solution_Name: SpeedTest.sln
      AspNet_Project_Path: Web/Web.csproj
      Test_Project_Path: WebTest/WebTest.csproj
      Infrastructure_Project_Path: Infrastructure/Infrastructure.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Exclude Desktop project from solution
      run: dotnet sln ${{ env.Solution_Name }} remove Desktop/Desktop.csproj

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build projects
      run: |
        dotnet build ${{ env.Infrastructure_Project_Path }} --configuration Release --no-restore
        dotnet build ${{ env.AspNet_Project_Path }} --configuration Release --no-restore
        dotnet build ${{ env.Test_Project_Path }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration Release --verbosity normal

    - name: Publish ASP.NET App
      run: dotnet publish ${{ env.AspNet_Project_Path }} -c Release -o ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildArtifacts
        path: ./publish
